import jsPDF from 'jspdf';

export function generateStudentReport(student) {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('GuardianLink - Student Monthly Report', 105, 20, { align: 'center' });
  
  // Student Info
  doc.setFontSize(12);
  doc.text(`Student Name: ${student.name}`, 20, 40);
  doc.text(`Email: ${student.email}`, 20, 50);
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, 60);
  
  // Performance Metrics
  doc.setFontSize(14);
  doc.text('Performance Metrics', 20, 80);
  doc.setFontSize(12);
  doc.text(`Attendance: ${student.attendance}%`, 20, 95);
  doc.text(`Marks (GPA): ${student.marks}%`, 20, 105);
  
  // Status
  const isAtRisk = student.attendance < 80 && student.marks < 60;
  doc.setFontSize(14);
  doc.text('Status', 20, 125);
  doc.setFontSize(12);
  
  if (isAtRisk) {
    doc.setTextColor(220, 53, 69);
    doc.text('⚠ AT RISK - Immediate intervention required', 20, 140);
  } else {
    doc.setTextColor(40, 167, 69);
    doc.text('✓ Good Standing', 20, 140);
  }
  
  // Color indicators
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text('Performance Indicators', 20, 165);
  doc.setFontSize(12);
  
  const attendanceColor = student.attendance >= 85 ? 'Green' : student.attendance >= 80 ? 'Yellow' : 'Red';
  const marksColor = student.marks >= 75 ? 'Green' : student.marks >= 60 ? 'Yellow' : 'Red';
  
  doc.text(`Attendance Status: ${attendanceColor}`, 20, 180);
  doc.text(`Marks Status: ${marksColor}`, 20, 190);
  
  // Footer
  doc.setFontSize(10);
  doc.text('Generated by GuardianLink System', 105, 280, { align: 'center' });
  
  // Save
  doc.save(`${student.name.replace(/\s+/g, '_')}_Report.pdf`);
}
